### ISSUE TITLE
plugin not found in sonarqube update center

### ISSUE THREAD

**Issue by thomas-mc-work** [racodond/sonar-jproperties-plugin#11]
Hello,

first thanks for this great idea and implementation of the plugin!

As I wanted to install the plugin I couldn't find it in the sonarqube update center as stated in the README file. I'm using sonarqube 5.1.2.

If this is known and not intended to change in the future then the documentation should be changed and maybe extended by a short installation description (or a link to the corresponding sonarqube documentation page).

Cheers

**Comment by racodond** [comment]
Hello,

> first thanks for this great idea and implementation of the plugin!

My pleasure ;-)

> As I wanted to install the plugin I couldn't find it in the sonarqube update center as stated in the README file. I'm using sonarqube 5.1.2. If this is known and not intended to change in the future then the documentation should be changed and maybe extended by a short installation description (or a link to the corresponding sonarqube documentation page).

Indeed, it's not yet in the Update Center... I hope it'll be soon though: https://groups.google.com/d/msg/sonarqube/TjpSl_yAJQY/X9aMn9esAAAJ. I updated the README file accordingly.

Thanks for your feedback

Cheers
