### ISSUE TITLE
Extend documentation for key-naming-convention

### ISSUE THREAD

**Issue by mkordas** [racodond/sonar-jproperties-plugin#3]
As it is currently the greatest tool available to validate `.properties` files in Java world, it will probably set some standards for the future.

There is one controversial rule though - key-naming-convention with its default value `^[a-z]+[-._a-z0-9]*$`.

There should be some reason given why this pattern was chosen as default setting. I've run this analysis on my project and it detected properties like `interface.jmsQueue.inbound.MarkitWire.replyTo=XXX`. Now, the developer seeing the violation would have no idea how it should be repaired, as the options are as follows:
- `interface.jms.queue.inbound.markit.wire.reply.to`
- `interface.jms_queue.inbound.markit_wire.reply_to`
- `interface.jms-queue.inbound.markit-wire.reply-to`

Example showing that `myKey` should be replaced with `my.key` doesn't help much in this case.

Moreover, I've found many standard JRE properties (from `jre/lib` directory) that use uppercase letters, e.g.:
- `javax.sound.sampled.SourceDataLine`
- `http.nonProxyHosts`
- `java.net.useSystemProxies`

So if the decision is that we aren't going to provide strict rules how to repair the above, let's allow uppercase letters in the pattern.

**Comment by racodond** [comment]
> As it is currently the greatest tool available to validate .properties files in Java world, it will probably set some standards for the future.

Thanks @mkordas for this nice feedback for a plugin that is only a couple of weeks old ;-)

> There is one controversial rule though - key-naming-convention with its default value ^[a-z]+[-._a-z0-9]*$.

Fully agree with you as Java properties files are used in a large variety of ways and by many frameworks.

> Now, the developer seeing the violation would have no idea how it should be repaired, as the options are

Again, I fully agree with you. The rule description should guide developers. Right now, it is not really helpful. 

> So if the decision is that we aren't going to provide strict rules how to repair the above, let's allow uppercase letters in the pattern.

From your feedback, I reworked the default regular expression and the rule description. See https://github.com/racodond/sonar-jproperties-plugin/pull/4. Tell me what you think.

Thanks

**Comment by mkordas** [comment]
> See #4. Tell me what you think.

Thanks, the proposition is still a bit controversial (as `-` and `_` are sometimes used even in `jre/lib/*.properties`), but at least it is now much clearer what is the recommended naming convention and how to fix violations.

However, people still will be wondering whether they should write `font.timesnewroman.size` (Java package style), `font.times.new.roman.size` (dots everywhere style), `font.timesNewRoman.size` (object-oriented with camel-case style) or `font.TimesNewRoman.size` (object oriented with class name style). Do you have any ideas how can we clarify also this?

**Comment by racodond** [comment]
> Thanks, the proposition is still a bit controversial (as - and _ are sometimes used even in jre/lib/*.properties), but at least it is now much clearer what is the recommended naming convention and how to fix violations.

It'll always be controversial. But I'm convinced that you can most of the times live without having to use '-' and '_'.

> However, people still will be wondering whether they should write font.timesnewroman.size (Java package style), font.times.new.roman.size (dots everywhere style), font.timesNewRoman.size (object-oriented with camel-case style) or font.TimesNewRoman.size (object oriented with class name style). Do you have any ideas how can we clarify also this?

I extended the description to tell developers to prefer `font.TimesNewRoman.size` to `font.timesnewroman.size`. Regarding `font.times.new.roman.size`, it does not follow OOP concept from my point of view, so it is already covered in the rule description. See https://github.com/racodond/sonar-jproperties-plugin/commit/e499ac18176eb5e654de22bdfce9b777f285fbfa.Tell me what you think.

**Comment by axel3rd** [comment]
First of all, thanks for the great job. This plugin is a very good idea.

+1 for letter in uppercase for `key-naming-convention` rule. 
Many components with 'correct' properties config file use it (sample : `log4j.properties`, `commons-logging.properties`

About `S1578` (_FileNameCheck_), IMO, `-` characters must be included in default pattern ... I don't want to be the one asking to _commons logging_ team to rename the properties file :-)

**Comment by racodond** [comment]
> First of all, thanks for the great job. This plugin is a very good idea.

Thanks :-)

> +1 for letter in uppercase for key-naming-convention rule. 
> Many components with 'correct' properties config file use it (sample : log4j.properties, commons-logging.properties

Good. I already moved that way.

> About S1578 (FileNameCheck), IMO, - characters must be included in default pattern ... I don't want to be the one asking to commons logging team to rename the properties file :-)

As it is also used by SonarQube (sonar-project.properties), I added '-' to the default regular expression.

**Comment by axel3rd** [comment]
@racodond Thanks !
