### ISSUE TITLE
New rule: Missing translations should be added in resource bundles

### ISSUE THREAD

**Issue by steve-price** [racodond/sonar-jproperties-plugin#68]
I might have missed it, but it would be useful if we were able to check for missing keys in files where there are multiple languages so that we catch missing translations.

**Comment by racodond** [comment]
Hi @steve-price,

Indeed, there's no such a rule for now.
It is a valuable rule. I'll try to implement it for next version.

David

**Comment by racodond** [comment]
Hi @steve-price,

It would be great if you could give a try to this rule by building a snapshot from https://github.com/racodond/sonar-jproperties-plugin/tree/issue_68_new_rule_missing_translations

David

**Comment by steve-price** [comment]
Hi David,

Apologies for not replying. Yes, I will make some time to give this a go. I
will email if i have any questions.

Thankd

Steve

**Comment by racodond** [comment]
@steve-price Cool! There's a snapshot available here to test: https://github.com/racodond/sonar-jproperties-plugin/releases/tag/2.3-RC1

**Comment by steve-price** [comment]
I could be wrong, but i dont think this is working out how I expected it to.  I have attached the files  I have used to test, there is a lot of them (I have included them in case it helps with debugging) but I will highlight the changes I have made to try and hit this new rule.
- I have checked that the snapshot has been installed correctly via the version on the plugins page
- I have made sure that the rule is included in the quality profile for the project
- In SecurityQuestions_en.properties I have duplicated SecurityQuestion.Q8 key and a jproperties:duplicated-keys issue was raised to I am confident that the files are being analysed.
- In SecurityQuestions_en.properties I have removed SecurityQuestion.Q9 which should be raised as an issue but I didnt see anything
- In the default file SecurityQuestions.properties I have removed SecurityQuestion.Q7 but I also didnt see anything

If there is any more information I can provide let me know.

Thanks

Steve
[TestProperties.zip](https://github.com/racodond/sonar-jproperties-plugin/files/524728/TestProperties.zip)

**Comment by racodond** [comment]
@steve-price Thanks a lot for your feedback! Big mistake on my side: forgot to copy a list before a `removeAll`... my integration tests have only two files with the same missing key and it was working in that case... I enriched my integration tests and a new snapshot is now available at https://github.com/racodond/sonar-jproperties-plugin/releases/tag/2.3-RC1. Looking forward to getting your feedback and my apologies for the inconvenience.

**Comment by racodond** [comment]
@steve-price Also, the rule does not raise an issue when a translation key is available in a localized file but not in the default. Would it make sense to you to have another rule detecting keys available in localized files but not in the default file?

**Comment by steve-price** [comment]
Hi @racodond ,
Thanks for the updated version, this works as described and looks good.  It would be useful to have a rule for the other way around as you mentioned.  I know that it might not be for everyone, but if you have a situation where the user is from a locale that we have translations for, then we are now covered by the new rule, but if they come from a locale that we don't have translations for then it will fall back to the default where we need all possible keys to be present so that they at least have some text, even if its not in there native language.  Does that make sense?

Thanks again for the effort.

**Comment by racodond** [comment]
Hi @steve-price,

> Thanks for the updated version, this works as described and looks good.

Great! Thanks for your feedback!

> It would be useful to have a rule for the other way around as you mentioned. I know that it might not be for everyone, but if you have a situation where the user is from a locale that we have translations for, then we are now covered by the new rule, but if they come from a locale that we don't have translations for then it will fall back to the default where we need all possible keys to be present so that they at least have some text, even if its not in there native language. Does that make sense?

Issue created for next version: https://github.com/racodond/sonar-jproperties-plugin/issues/70
I'll ping you when it is available so that you can give it a try.

> Thanks again for the effort.

My pleasure!
