### ISSUE TITLE
Add rule: Duplicated keys across files

### ISSUE THREAD

**Issue by racodond** [racodond/sonar-jproperties-plugin#7]

**Comment by mkordas** [comment]
David, many projects contain properties files with duplicate entries on purpose for different environments, e.g.:

```
staging/common.properties
prod/common.properties
```

or

```
staging.properties
prod.properties
```

Do you have any plans how to not trigger violations on such files?

**Comment by racodond** [comment]
@mkordas Yep, you would just have to set exclusions on such files (environment properties, i18n files, etc.) It is explained in the description of the rule. I should push my local branch very soon. So that you can give it a try if you want and provide some feedback. Also, this rule is not activated by default.

**Comment by racodond** [comment]
@mkordas Pushed to master if you want to give it a try.

**Comment by racodond** [comment]
Fixed in https://github.com/racodond/sonar-jproperties-plugin/commit/4adeeddef242ee79b9425b9baee37ae7e7cdb645
