### ISSUE TITLE
New rule: All translation keys defined in locale resource bundles should also be defined in the default resource bundle

### ISSUE THREAD

**Issue by racodond** [racodond/sonar-jproperties-plugin#70]
Add a "See also" section in the rule description to link to rule "Missing translations should be added in resource bundles". And the other way around on "Missing translations should be added in resource bundles" rule description.

**Comment by racodond** [comment]
@steve-price: Feel free to test the snapshot at https://github.com/racodond/sonar-jproperties-plugin/releases/tag/%2370 and provide some feedback.

**Comment by steve-price** [comment]
Thanks David.

I will put that in when i have a moment.
