### ISSUE TITLE
Credentials should not be hard-coded(jproperties:S2068) - Add the ability to ignore encrypted values

### ISSUE THREAD

**Issue by pethers** [racodond/sonar-jproperties-plugin#73]
Get some false positives, example below.

Example : https://www.hack23.com/sonar/dashboard/index?id=com.hack23.cia%3Acitizen-intelligence-agency%3Asrc%2Fmain%2Fresources%2Fdatabase.properties

Using jasypt to encrypt properties, so properties look like below

database.username=ENC(mhIlYMOihCo/21ZXovWUFAkUwVbY5jtZm6/CpouvDsY=)

and are loaded using a EncryptablePropertyPlaceholderConfigurer.

Would it be possible to ignore the rule for some prefixes of values ? 

Other prefixes used by jetty https://wiki.eclipse.org/Jetty/Howto/Secure_Passwords .

Best regards

**Comment by racodond** [comment]
Hi @pethers,

Sure I can add value prefix for this rule not to raise issues. I cannot find the prefixes on the page you mentionned. From tour example, I can exclude values starting with ENC( but what are the others?

Thanks

**Comment by pethers** [comment]
Thanks for the rapid response.

Would be happy with just support for ENC(), jasypt seems to be the most popular solution.

Jetty uses OBF: , MD5: or CRYPT: prefix on the generated password. OBF are obfuscated, and are used by some other projects as well.

All the best

**Comment by racodond** [comment]
Ah OK.

**Comment by racodond** [comment]
By default, I won't make the rule ignore those encrypted values. I'll add a parameter (regular expression of encrypted values to ignore) instead.

**Comment by pethers** [comment]
A parameter sounds good, a more flexible solution as well.

**Comment by racodond** [comment]
Hi @pethers, 

Here's a snapshot including the fix: https://github.com/racodond/sonar-jproperties-plugin/releases/tag/%2373.

Feel free to test it and provide some feedback.

Thanks

David

**Comment by pethers** [comment]
Excellent, updated the plugin and configured the parameter. 

Will now if it worked once the build is completed, at https://www.hack23.com/sonar/dashboard/index?id=com.hack23.cia%3Acitizen-intelligence-agency%3Asrc%2Fmain%2Fresources%2Fdatabase.properties . Made a mistake entering the the parameter with quotes '^(ENC\(|OBF:).+$' . Will test it again after work.

**Comment by pethers** [comment]
Tested it now and it works as expected with correct parameter value. Used '^ENC(.+$)|OBF:.+$' in the end as parameter value.

Thanks for all the help.

**Comment by racodond** [comment]
Cool! Thanks for your feedback!
