### ISSUE TITLE
Make the plugin compatible with SonarQube 6.7

### ISSUE THREAD

**Issue by racodond** [racodond/sonar-jproperties-plugin#77]

**Comment by kthieling** [comment]
Is there some reason 2.6 is not showing up in the Marketplace for SonarQube 6.7?

**Comment by racodond** [comment]
Hi @kthieling,

Due to disagreements with SonarSource, I stepped out of the community.
So, you now need to manually install this plugin as well as all the others I maintain: CSS, Gherkin, JSON...

David

**Comment by bhaberle** [comment]
Hi David

Do your Sonar plugins work in 7.x?

**Comment by racodond** [comment]
Hi @bhaberle,

Yes, they work except for custom rules.

David
